import type { Collection, Product, User } from "./types";

export const SEED_COLLECTIONS: Collection[] = [
  {
    id: "col-new-arrivals",
    name: "New Arrivals",
    slug: "new-arrivals",
    description: "The latest drops, fresh from the print shop.",
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "col-classics",
    name: "Classics",
    slug: "classics",
    description: "Timeless stacks that never go out of style.",
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "col-ai-drop",
    name: "AI Drop",
    slug: "ai-drop",
    description: "Wear the models that changed everything.",
    createdAt: "2026-06-15T00:00:00.000Z",
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: "prod-python-shirt",
    name: "Python Classic Tee",
    description:
      "Soft cotton tee with the Python logo front and center. Indentation not included.",
    garment: "shirt",
    stack: "languages",
    tech: "Python",
    price: 449,
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "#1a1a1a",
    logo: "/logos/python.svg",
    images: [],
    collectionId: "col-classics",
    featured: true,
    status: "active",
    createdAt: "2026-05-02T00:00:00.000Z",
  },
  {
    id: "prod-ts-shirt",
    name: "TypeScript Strict Tee",
    description:
      "For those who never use any. Blue square, big energy, fully typed comfort.",
    garment: "shirt",
    stack: "languages",
    tech: "TypeScript",
    price: 449,
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "#f5f5f5",
    logo: "/logos/typescript.svg",
    images: [],
    collectionId: "col-classics",
    featured: true,
    status: "active",
    createdAt: "2026-05-03T00:00:00.000Z",
  },
  {
    id: "prod-js-shirt",
    name: "JavaScript OG Tee",
    description:
      "The language that runs the web, on the shirt that runs your wardrobe.",
    garment: "shirt",
    stack: "languages",
    tech: "JavaScript",
    price: 429,
    sizes: ["S", "M", "L", "XL"],
    color: "#1a1a1a",
    logo: "/logos/javascript.svg",
    images: [],
    collectionId: "col-classics",
    status: "active",
    createdAt: "2026-05-04T00:00:00.000Z",
  },
  {
    id: "prod-react-hoodie",
    name: "React Atomic Hoodie",
    description:
      "Heavyweight hoodie with the atom everyone re-renders for. Hooks sold separately.",
    garment: "hoodie",
    stack: "frontend",
    tech: "React",
    price: 899,
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "#1a1a1a",
    logo: "/logos/react.svg",
    images: [],
    collectionId: "col-new-arrivals",
    featured: true,
    status: "active",
    createdAt: "2026-06-02T00:00:00.000Z",
  },
  {
    id: "prod-vue-shirt",
    name: "Vue Progressive Tee",
    description: "Approachable, performant, versatile. Also, it's green.",
    garment: "shirt",
    stack: "frontend",
    tech: "Vue",
    price: 429,
    sizes: ["S", "M", "L", "XL"],
    color: "#f5f5f5",
    logo: "/logos/vuejs.svg",
    images: [],
    status: "active",
    createdAt: "2026-05-10T00:00:00.000Z",
  },
  {
    id: "prod-tailwind-sweater",
    name: "Tailwind Utility Sweater",
    description:
      "flex items-center justify-cozy. A utility-first sweater for utility-first people.",
    garment: "sweater",
    stack: "frontend",
    tech: "Tailwind CSS",
    price: 749,
    sizes: ["S", "M", "L", "XL"],
    color: "#1a1a1a",
    logo: "/logos/tailwindcss.svg",
    images: [],
    collectionId: "col-new-arrivals",
    status: "active",
    createdAt: "2026-06-05T00:00:00.000Z",
  },
  {
    id: "prod-nextjs-hoodie",
    name: "Next.js Edge Hoodie",
    description:
      "Server-rendered warmth with zero layout shift. Ships instantly to your closet.",
    garment: "hoodie",
    stack: "frontend",
    tech: "Next.js",
    price: 949,
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "#1a1a1a",
    logo: "/logos/nextjs.svg",
    images: [],
    collectionId: "col-new-arrivals",
    featured: true,
    status: "active",
    createdAt: "2026-06-10T00:00:00.000Z",
  },
  {
    id: "prod-node-shirt",
    name: "Node.js Runtime Tee",
    description: "Non-blocking, event-driven, machine-washable.",
    garment: "shirt",
    stack: "backend",
    tech: "Node.js",
    price: 449,
    sizes: ["S", "M", "L", "XL"],
    color: "#1a1a1a",
    logo: "/logos/nodejs.svg",
    images: [],
    status: "active",
    createdAt: "2026-05-12T00:00:00.000Z",
  },
  {
    id: "prod-go-shirt",
    name: "Go Gopher Tee",
    description: "Concurrency you can wear. Goroutines not included, gopher is.",
    garment: "shirt",
    stack: "backend",
    tech: "Go",
    price: 449,
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "#f5f5f5",
    logo: "/logos/go.svg",
    images: [],
    status: "active",
    createdAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "prod-rust-hoodie",
    name: "Rust Fearless Hoodie",
    description:
      "Memory-safe warmth with zero-cost abstractions. The borrow checker approves.",
    garment: "hoodie",
    stack: "languages",
    tech: "Rust",
    price: 899,
    sizes: ["S", "M", "L", "XL"],
    color: "#1a1a1a",
    logo: "/logos/rust.svg",
    images: [],
    collectionId: "col-classics",
    status: "active",
    createdAt: "2026-05-20T00:00:00.000Z",
  },
  {
    id: "prod-docker-cap",
    name: "Docker Container Cap",
    description: "Works on your head. Works on every head. That's the point.",
    garment: "cap",
    stack: "devops",
    tech: "Docker",
    price: 349,
    sizes: ["M", "L"],
    color: "#1a1a1a",
    logo: "/logos/docker.svg",
    images: [],
    status: "active",
    createdAt: "2026-05-22T00:00:00.000Z",
  },
  {
    id: "prod-k8s-sweater",
    name: "Kubernetes Helm Sweater",
    description:
      "Self-healing comfort that scales with you. Warmth orchestrated across all pods.",
    garment: "sweater",
    stack: "devops",
    tech: "Kubernetes",
    price: 779,
    sizes: ["S", "M", "L", "XL"],
    color: "#1a1a1a",
    logo: "/logos/kubernetes.svg",
    images: [],
    status: "active",
    createdAt: "2026-05-25T00:00:00.000Z",
  },
  {
    id: "prod-git-cap",
    name: "Git Commit Cap",
    description: "git checkout style. Merge conflicts with your outfit resolved.",
    garment: "cap",
    stack: "tools",
    tech: "Git",
    price: 329,
    sizes: ["M", "L"],
    color: "#1a1a1a",
    logo: "/logos/git.svg",
    images: [],
    status: "active",
    createdAt: "2026-05-28T00:00:00.000Z",
  },
  {
    id: "prod-linux-shirt",
    name: "Linux Tux Tee",
    description: "The penguin that powers the internet, now powering your look.",
    garment: "shirt",
    stack: "tools",
    tech: "Linux",
    price: 449,
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "#f5f5f5",
    logo: "/logos/linux.svg",
    images: [],
    status: "active",
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "prod-pytorch-hoodie",
    name: "PyTorch Gradient Hoodie",
    description:
      "Backpropagate warmth through every layer. Autograd for your torso.",
    garment: "hoodie",
    stack: "ai-ml",
    tech: "PyTorch",
    price: 929,
    sizes: ["S", "M", "L", "XL"],
    color: "#1a1a1a",
    logo: "/logos/pytorch.svg",
    images: [],
    collectionId: "col-ai-drop",
    featured: true,
    status: "active",
    createdAt: "2026-06-16T00:00:00.000Z",
  },
  {
    id: "prod-graphql-shirt",
    name: "GraphQL Query Tee",
    description: "Ask for exactly what you want. Get exactly this shirt.",
    garment: "shirt",
    stack: "backend",
    tech: "GraphQL",
    price: 449,
    sizes: ["S", "M", "L", "XL"],
    color: "#f5f5f5",
    logo: "/logos/graphql.svg",
    images: [],
    collectionId: "col-new-arrivals",
    status: "active",
    createdAt: "2026-06-18T00:00:00.000Z",
  },
];

export const SEED_USERS: User[] = [
  {
    id: "user-admin",
    name: "Olmeware Admin",
    email: "admin@olmeware.store",
    password: "admin123",
    role: "admin",
    createdAt: "2026-05-01T00:00:00.000Z",
  },
];
